### PR TITLE
Dot1x rules setup

### PR DESCRIPTION
**Pull request by Bairdo**
- uses the port.dot1x flag to install rules on the port_acl table.
- adds valve.dot1x.nfv_sw_port to set the output port (nfv location). -- this can be different for each dp (unlike the radius options and nfv_intf).
- tests also had an error (wrong host was pinging).

### CODE REVIEW

**Comment by anarkiwi** [comment]
Looks like failing due to lint?

**Comment by Bairdo** [comment]
ugh 
d804d80 (notify chewie of port down) wasn't supposed to be in this pr

**Comment by Bairdo** [comment]
think that's sorted.

**Comment by anarkiwi** [comment]
Looks like a __slots__ conflict.

File "/faucet-src/faucet/valve.py", line 104, in __init__: Can't assign attribute 'dot1x' on Valve [not-writable]
File "/faucet-src/faucet/valve.py", line 105, in __init__: Can't assign attribute 'dp' on Valve [not-writable]
File "/faucet-src/faucet/valve.py", line 1366, in _apply_config_changes: Can't assign attribute 'dp' on Valve [not-writable]
Traceback:
  line 1434, in reload_config
File "/faucet-src/faucet/valve.py", line 1372, in _apply_config_changes: Can't assign attribute 'dp' on Valve [not-writable]
File "/faucet-src/faucet/valve.py", line 1394, in _apply_config_changes: Can't assign attribute 'dp' on Valve [not-writable]
For more details, see https://github.com/google/pytype/blob/master/docs/errors.md#not-writable.

**Comment by Bairdo** [comment]
I might've just fixed it

**Pull request merged**
