### PR TITLE
WIP: Prioritise selected link over standby

### PR DESCRIPTION
**Pull request by anurag6**
Change-Id: I5a78a9812e60202aee96d6b06afbc2fd014acabd

### CODE REVIEW

**Comment by gizmoguy** [comment]
Hey @mab68, when you are free.

The intended behavior of this PR is that when a port is configured as `lacp_standby: True` we want to short circuit the state machine a little and have it end up with the lacp sync bit set, but not collect or distribute. So that when the backup link needs to take over it doesn't have to go sync --> C&D, it can just jump to C&D.

Is this PR going to do that? Or do we need to do more.

**Comment by mab68** [comment]
@gizmoguy 

https://github.com/mab68/faucet/commit/845be8a3df4fdabb9c3abea93493aa23f0945424 should accomplish what you want.

**Comment by gizmoguy** [comment]
Ah, great. That looks good to me, want to push it up as a PR that superseeds this one?

Thanks!

**Comment by mab68** [comment]
superseeded by #3501

**Pull request closed without merging**
