### PR TITLE
 adds a rabbitmq adapter to get events from the socket

### PR DESCRIPTION
**Pull request by cglewis**
- updates the FAUCET_EVENT_SOCK to be a file that lives in
/var/run so that volume mounts can be set for docker containers

- intended to be used with docker-compose by just adding additional yaml files to the command

- add tests and docs for the specific adapter

- add docs for more vendored adapters in the future

- if using a given adapter additional environment variables are used and prefixed with FA for FAUCET Adapter

see issue #1312

### CODE REVIEW

**Comment by cglewis** [comment]
@gizmoguy Since you can't make a Docker volume that can share between containers as just a single file, I am putting into a dedicated folder (`/var/run/faucet/faucet.sock`), so that only that `faucet.sock` file inside the `faucet` dir is shared.  I also made `FAUCET_EVENT_SOCK` a bool to simplify that.  Let me know if that looks better.

**Comment by cglewis** [comment]
looks like the markdown doesn't directly translate to rst. I'll fix that up and push up

**Comment by gizmoguy** [comment]
@cglewis perfect! looks great now, thanks for those tweaks.

**Comment by gizmoguy** [comment]
@cglewis I've kicked off a docker build for the new Dockerfile, hopefully it will be up here soon:

https://hub.docker.com/r/faucet/faucet-event-adapter-rabbitmq/

**Comment by cglewis** [comment]
sweet!

**Pull request merged**
