### PR TITLE
Use max_lldp_lost properly

### PR DESCRIPTION
**Pull request by grafnu**
Fixes bug to enable easy workaround for https://github.com/faucetsdn/faucet/issues/3281

### CODE REVIEW

**Comment by anarkiwi** [comment]
Please add a test that shows that the parameters are used correctly.

**Comment by anarkiwi** [comment]
Thanks that's better, and it shows the parameter can be parsed, but it doesn't show that the parameter is acted on?

**Comment by grafnu** [comment]
Updated with a comment explaining how the test tests behavior... PTAL.

**Comment by anarkiwi** [comment]
I don't see how the max lldp port option is tested still?

**Comment by grafnu** [comment]
Updated with more comments, ptal. I know the behavioral test is there, but
it is admittedly buried somewhat down in the testing library (the use of
LLDP beacons). Not sure if there's a better way...

**Comment by anarkiwi** [comment]
I still don't see how the parameter fix works, though? I'm looking for a test that shows, that you can set a particular number (like 100), and that we wait the appropriate number of lost packets.

**Comment by grafnu** [comment]
I made the number of packets it was waiting for more explicit, so the bounds should be clear. First it's testing the default behavior (3), and then sets the value to 100 and tests the new behavior...

**Pull request merged**
