### PR TITLE
packets on stacking ports are marked as external_loop_protect (vlan_pcp=0) even when they're not.

### PR DESCRIPTION
**Pull request by grafnu**
One half of a problem I've been tracking down. I have it distilled down to a test, but haven't identified the solution yet. The problem is that the actions generated for stacking ports on a switch set the vlan_pcp=0, which implicitly makes them considered "external" by the receiving switch. It breaks, then, internal --> external communication across the stack.

If you can point me roughly at where in the code this happens, I'd be most appreciative and can fix it up. Otherwise I'll keep on looking... I just haven't found where the rule actions are constructed yet...

### CODE REVIEW

**Comment by anarkiwi** [comment]
How does this PR relate to https://github.com/faucetsdn/faucet/pull/2884?

**Comment by grafnu** [comment]
It's the same test case as #2884 (external ports on different switches), but a different issue and root cause. I've updated the title of both to be more descriptive.  This does not yet have a proposed fix, just a failing test -- I'm still trying to figure out the right fix.

**Comment by grafnu** [comment]
Ok -- I updated the PR with a working fix for the stack-size-2 case. I wanted to get your feedback before generalizing to the non-size-2 code.

I also don't understand the case where there is no in_port on the flow -- and not sure how to handle it properly.

**Comment by anarkiwi** [comment]
Thanks! The problem description is much clearer. 

We have an overall goal of using the minimum number of flows. Flooding is the most expensive in terms of flows that use a lot of instructions (a lot of output actions). So we attempt to only generate per-port flooding rules when absolutely necessary, and have a lower priority "no port" flow to handle the default case. If a correct per port flow is being discarded in favor of the incorrect default case flow, then the right approach is to fix the logic that causes the per port flow to be discarded (at the moment it compares some actions and output ports, but perhaps it is wrong here). 

A way to debug this further - you can turn on combinatorial flood mode:

combinatorial_port_flood: True

This forces the per-port flow to be used always. If that results in correct behavior, that confirms that the per-port rule is being incorrectly discarded.

**Comment by grafnu** [comment]
Ah, the question/problem wasn't "that the per-port rule is being incorrectly discarded", but rather that I didn't understand what that bit of code was doing (in_port == None) so wasn't sure what to do with it. 

Can you PTAL at the PR fix and let me know if it's headed in the right direction?  It's only done for the stack2 case, and if it's more-or-less correct, I'd proceed to testing/fixing the other cases (n > 2) and properly testing the default flood rule (which hits some weird corner cases with external ports, maybe).

**Pull request merged**
