### PR TITLE
Ordered ACL output actions

### LINKED ISSUE #3314: Dynamic named tunnel VLANs
Currently it is required to create a tunnel with an unused VLAN. That's great, as it's unlikely a network is going to have completely saturated all VLANs.  However, it presents the problem of having to specify one to reserve manually and hope that the operator or application didn't use a VLAN already in use.

Since Faucet will have full knowledge of the VLANs already in use, I propose using unqiue names for the IDs and behind the scenes Faucet picks an unused VLAN, which may change upon config reload (since reloading could introduce new VLANs).

Currently this looks like where the VLAN number is specified:
```
acls:
  tunnel-to-host1:
    - rule:
      action:
      output:
        tunnel:
          type: 'vlan'
          tunnel_id: 901
          dp: x230
          port: 1
        allow: 1
```

Or this where the name of the VLAN is specified and defined:
```
acls:
  tunnel-to-host1:
    - rule:
      action:
      output:
        tunnel:
          type: 'vlan'
          tunnel_id: foo
          dp: x230
          port: 1
        allow: 1
vlans:
  foo:
    vid: 100
```

What I'm proposing as an option (or replacement, maybe) would be to be able to do this (or something like this):
```
acls:
  tunnel-to-host1:
    - rule:
      action:
      output:
        tunnel:
          type: 'vlan'
          tunnel_id: foo
          dp: x230
          port: 1
        allow: 1
```
And behind the scenes Faucet would pick a `vid` not in use.

### LINKED ISSUE #3389: stack tunnelled traffic and 'allow:true' doesn't produce expected results
When using a tunnel ACL (with allow:true) to tunnel traffic to a to a remote egress switch, it appears that the expected allow:true processing for certain egress traffic flows does not occur.

Using a network configuration like the following

```
host12 -- sw1 ==== sw3 -- host31
           |
           |
      host199 (tunnel egress)
```

with the following faucet.yaml against 2 OVS bridge instances:

```
acls:
  tunnel-udp:
    - rule:
        dl_type: 0x0800         # IPv4
        nw_proto: 17            # UDP
        actions:
          output:
            tunnel:
              type: 'vlan'
              tunnel_id: 4010
              dp: sw1
              port: 99
          allow: true


vlans:
  home:
    vid: 100

dps:
  sw1:
    dp_id: 0x1
    hardware: "Open vSwitch"
    stack:
      priority: 1
    interfaces:
      1:
        native_vlan: home
      10:
        stack:
          dp: sw3
          port: 10
      99:
        description: monitoring port
        output_only: true
  sw3:
    dp_id: 0x3
    hardware: "Open vSwitch"
    interfaces:
      1:
        native_vlan: home
        acls_in: [tunnel-udp]
      10:
        stack:
          dp: sw1
          port: 10
```

Injecting L2 flooded UDP traffic on sw3/1, this traffic gets tunnelled to sw1/99, as expected. But, the traffic is not L2 forwarded to the other ports in the vlan on remote DPs - eg sw1/1, as I was expecting given the 'allow:true' in the ACL.

But, by removing the 'acls_in' stanza from sw3/1, this allows the ingress UDP traffic on sw3/1 to be L2 forwarded to sw1/1 correctly.

With the original config, I see the following OF rules in sw3:

```
vagrant@faucet-u1804:~$ sudo ovs-ofctl dump-flows br3
 cookie=0x5adc15c0, duration=369.185s, table=0, n_packets=38, n_bytes=3720, priority=20480,in_port="l-br3_10-br1_10" actions=resubmit(,1)
 cookie=0x5adc15c0, duration=364.242s, table=0, n_packets=24, n_bytes=1008, priority=20480,udp,in_port="veth-host31" actions=mod_vlan_vid:4010,output:"l-br3_10-br1_10",resubmit(,1)
...
 cookie=0x5adc15c0, duration=369.180s, table=1, n_packets=0, n_bytes=0, priority=9000,in_port="veth-host31",vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:100,resubmit(,2)
 cookie=0x5adc15c0, duration=369.174s, table=1, n_packets=24, n_bytes=1008, priority=0 actions=drop
...
 cookie=0x5adc15c0, duration=364.229s, table=2, n_packets=0, n_bytes=0, priority=4096,dl_vlan=100 actions=CONTROLLER:96,resubmit(,3)
 cookie=0x5adc15c0, duration=364.229s, table=2, n_packets=0, n_bytes=0, priority=4096,dl_vlan=4010 actions=CONTROLLER:96,resubmit(,3)
...
 cookie=0x5adc15c0, duration=369.175s, table=3, n_packets=0, n_bytes=0, priority=0 actions=resubmit(,4)
...
 cookie=0x5adc15c0, duration=364.242s, table=4, n_packets=0, n_bytes=0, priority=8240,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:"l-br3_10-br1_10",strip_vlan,output:"veth-host31"
```

While, without the tunnel ACL applied, sw3 shows the following flows, which works for UDP traffic stream:

```
vagrant@faucet-u1804:~$ sudo ovs-ofctl dump-flows br3
 cookie=0x5adc15c0, duration=26.521s, table=0, n_packets=0, n_bytes=0, priority=9001,in_port="l-br3_10-br1_10",vlan_tci=0x0000/0x1fff actions=drop
 cookie=0x5adc15c0, duration=26.519s, table=0, n_packets=15, n_bytes=630, priority=9000,in_port="veth-host31",vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:100,resubmit(,2)
...
 cookie=0x5adc15c0, duration=16.188s, table=2, n_packets=14, n_bytes=588, hard_timeout=282, priority=8191,in_port="veth-host31",dl_vlan=100,dl_src=4e:9f:83:7e:7d:ee actions=resubmit(,3)
 cookie=0x5adc15c0, duration=25.525s, table=2, n_packets=1, n_bytes=42, priority=4096,dl_vlan=100 actions=CONTROLLER:96,resubmit(,3)
 cookie=0x5adc15c0, duration=25.525s, table=2, n_packets=0, n_bytes=0, priority=4096,dl_vlan=4010 actions=CONTROLLER:96,resubmit(,3)
...
 cookie=0x5adc15c0, duration=26.518s, table=3, n_packets=15, n_bytes=630, priority=0 actions=resubmit(,4)
...
 cookie=0x5adc15c0, duration=25.536s, table=4, n_packets=15, n_bytes=630, priority=8240,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:"l-br3_10-br1_10",strip_vlan,output:"veth-host31"
```

Looking at the failing flows again, I suspect the issue is with this flow:

>  cookie=0x5adc15c0, duration=364.242s, table=0, n_packets=24, n_bytes=1008, priority=20480,udp,in_port="veth-host31" actions=mod_vlan_vid:4010,output:"l-br3_10-br1_10",resubmit(,1)

interacting with this flow:

>  cookie=0x5adc15c0, duration=369.180s, table=1, n_packets=0, n_bytes=0, priority=9000,in_port="veth-host31",vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:100,resubmit(,2)

I believe the mod_vlan_vid:4010 causes the vlan_tci=0x0000/0x1fff match to fail, so then:

> cookie=0x5adc15c0, duration=364.242s, table=4, n_packets=0, n_bytes=0, priority=8240,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:"l-br3_10-br1_10",strip_vlan,output:"veth-host31"

doesn't get matched / executed either.

### LINKED ISSUE #3468: Faucet ACL ambiguity & allowing badly defined ACLs
Currently Faucet happily accepts ACLs of the following form:
```
acls:
    funky_acl:
        - rule:
            dl_vlan: 100
            actions:
                allow: 1
                output:
                    vlan_vid: 5
                    port: 2
                    pop_vlans: 1
                    ports: [3]
                    vlan_vids: [6, 7]
```
Which compiles to the following flowrule:
```
in_port="veth-host1",dl_vlan=100 actions=strip_vlan,mod_vlan_vid:5,output:"veth-host2",output:"veth-host3",resubmit(,1)
```

There are two problems with this
- Faucet does not accept duplicate keys but does accept the different forms of the same action ie: vlan_vid & vlan_vids.
- Faucet specifically applies actions based on some non-sequential order. For example VLAN header based ACLs are always applied first.

I would personally expect for ACL actions to be applied in order, having Faucet quietly decide to move actions around might create some problems for the user. I also think there should not be a problem with having duplicate keys in an output action.

### PR DESCRIPTION
**Pull request by mab68**
Allow ordered ACL output actions as mentioned in #3468 (Closes #3468).
```
acls:
    ordered_acl:
        - rule:
            dl_vlan: 100
            actions:
                output:
                    - port: 2
                    - pop_vlans: 1
                    - port: 3
```

Fix #3389 

Allow defining a tunnel without requiring a VLAN, Faucet will pick an unused VID that is larger than the configured VIDs (Closes #3314).
e.g.: The following config will create a tunnel that will be encapsulated with VID 101
```
vlans:
  vlans:
    vlan100:
      vid: 100
acls:
  tunnel-to-host1:
    - rule:
      actions:
      output:
        tunnel:
          dp: sw1
          port: 1
```

Tunnel ACLs will pop off the encapsulation after the output action so rules can now be applied after a tunnel action. e.g.: The output to port 6 will not have the tunnel VID applied
```
acls:
  tunnel_acl:
    - rule:
      ip_proto: 1
      dl_type: 0x0800
      actions:
        output:
          - port: 5
          - tunnel: {dp: sw2, port: 1}
          - port: 6
```

### CODE REVIEW

**Comment by anarkiwi** [comment]
Looking into the test failures now - looks like config change detection problems revealed by my refactoring.

**Comment by anarkiwi** [comment]
Will fix - sorry for the inconvenience.

**Comment by anarkiwi** [comment]
Should be all sorted now. The FaucetUntaggedPortSwapIPv4InterVLANRouteTest flake is fixed by  https://github.com/faucetsdn/faucet/pull/3487

**Comment by mab68** [comment]
This is all sorted on my part too.

**Comment by gizmoguy** [comment]
LGTM now :+1:

**Pull request merged**
