### PR TITLE
hotfix changing FAUCET_EVENT_SOCK to a bool

### PR DESCRIPTION
**Pull request by cglewis**
previous merged PR broke the build, this fixes my mistake

### CODE REVIEW

**Comment by cglewis** [comment]
@gizmoguy looks like this didn't quite fix it either. hmm. looking to see if I can figure out what I broke...

**Comment by gizmoguy** [comment]
@anarkiwi is working on it, he should have a PR up soon

Your dockerfile doesn't build at the moment either due to missing dependencies, I'll have a PR up shortly to correct.

**Comment by gizmoguy** [comment]
#1374

Other PR is on it's way shortly

**Comment by anarkiwi** [comment]
Oh! I also have something in flight to fix this. Don't worry I'm on it.

**Comment by cglewis** [comment]
@gizmoguy @anarkiwi sorry about that! i think i found another test I didn't update, but am running travis on my fork so I don't keep submitting incomplete PRs!  I'm not sure #1374 is actually necessary.

**Comment by anarkiwi** [comment]
All good, tests FTW. :)

I've busted the build a bit recently myself, only just got around to fixing
up my precommit hooks so it's harder for me to do that now.

**Pull request merged**
