### PR TITLE
CodeCheck - Part2b

### PR DESCRIPTION
**Pull request by mwutzke**
More horizontal white-space / alignment cleanups

### CODE REVIEW

**Review by cglewis — APPROVED** [review]

**Comment by cglewis** [comment]
I can’t see why this PR would cause the integration test to fail. Must be a flake?

**Comment by mwutzke** [comment]
My local re-run passes as well:
```
test results
============
---
mininet_multidp_tests.FaucetSingleStackStringOfDPTagged0Test.test_dp_root_hop_port:
  output: ''
  status: OK
  test_duration_secs: 62
...
```

**Comment by cglewis** [comment]
@mwutzke looks like retriggering passed. If you could open an issue so we can track the flake, I can merge this in for now.

**Comment by mwutzke** [comment]
Created issue #3908 to track the earlier test run failure.

**Pull request merged**
