### PR TITLE
add a dockerfile for rabbitmq-adapter on raspberry pi

### PR DESCRIPTION
**Pull request by Bairdo**
I will need to test this actually runs correctly on pi network on Monday, but it does build. Think it did yesterday but not certain.

### CODE REVIEW

**Comment by cglewis** [comment]
nice. I don't have a way to verify over the weekend either, but it looks good from a cursory look.  thanks for adding this.

**Comment by Bairdo** [comment]
Checked on my setup and it runs fine.

**Comment by gizmoguy** [comment]
Hi folks, we now build this docker on our raspberry pi build farm so you can pull straight from docker hub now:

https://hub.docker.com/r/faucet/faucet-event-adapter-rabbitmq-pi/

**Comment by toiletduck123** [comment]
Hey guys, I am trying to run rabbitmq on my Raspberry Pi which is running Faucet however I am encountering an error.

When I run the following command:
```
docker-compose -f docker-compose.yaml \
               -f adapters/vendors/rabbitmq/docker-compose.yaml \
               up
```

I get an error:
```
standard_init_linux.go:190: exec user process caused "exec format error"
ERROR: Service 'faucet' failed to build: The command '/bin/sh -c ./faucet-src/docker/install-faucet.sh' returned a non-zero code: 1
```

Any indication as to why I might be getting this? I am stumped.  Faucet has been running and operating fine on my RPi, not sure why rabbitmq won't work!

Thanks in advance

**Comment by toiletduck123** [comment]
Just to clarify, that error comes after:

```
Step 3/6 : RUN ./faucet-src/docker/install-faucet.sh
 ---> Running in 64113003e3ea
```

When I build my normal Faucet container and it has to do Step 3/6 in relation to install-faucet.sh, it succeeds and works fine.

**Comment by gizmoguy** [comment]
Ah sorry @toiletduck123 you've fallen into an unintentional pitfall I left. The docker-compose.yaml files in our repo will run amd64 compiled docker images (unsuitable for raspberry pi which is arm based)

In #2099 I've added the missing docker-compose file that will use our docker images which are compiled for armhf.

I suspect a command similar to this will get you up and running:

> docker-compose -f docker-compose-pi.yaml \
>                -f adapters/vendors/rabbitmq/docker-compose-pi.yaml \
>                up

**Comment by toiletduck123** [comment]
Thank you very much! That is it up and running now

**Comment by toiletduck123** [comment]
Just a quick follow up question.  The reason I wanted to install RabbitMQ was to determine whether faucet was sending out appropriate event messages (as my external Machine Learning application wasn't picking anything up from the controller such as clients etc).

The logs show:

```
faucet_1            | 172.18.0.7 - - [19/Jun/2018 12:42:32] "GET /metrics HTTP/1.1" 200 7659 0.022145
faucet_1            | 172.18.0.7 - - [19/Jun/2018 12:42:47] "GET /metrics HTTP/1.1" 200 7659 0.015152
faucet_1            | 172.18.0.7 - - [19/Jun/2018 12:43:02] "GET /metrics HTTP/1.1" 200 7659 0.011069
faucet_1            | 172.18.0.7 - - [19/Jun/2018 12:43:17] "GET /metrics HTTP/1.1" 200 7646 0.010862
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
rabbitmq_adapter_1  | Not connecting to any RabbitMQ, host is None.
rabbitmq_adapter_1  | Starting with UID=0 GID=0
```

And keep repeating like this.  Is there anywhere I could find out how to debug this and determine the output from Faucet?

Thanks

**Comment by toiletduck123** [comment]
Additional info, that is after running:

**Comment by toiletduck123** [comment]
Additional info, that is after running:

```
export FA_RABBIT_HOST=
export FA_RABBIT_PORT=5672
export FA_RABBIT_EXCHANGE=topic_recs
export FA_RABBIT_EXCHANGE_TYPE=topic
export FA_RABBIT_ROUTING_KEY=FAUCET.event

docker-compose -f docker-compose-pi.yaml \
               -f adapters/vendors/rabbitmq/docker-compose-rabbitmq.yaml \
               -f adapters/vendors/rabbitmq/docker-compose-pi.yaml \
               up
```

**Comment by cglewis** [comment]
your `export FA_RABBIT_HOST=` needs to be set to the IP address of where your RabbitMQ server is running. in this case, since you're running it all through `docker-compose` it should just be the IP of your RPi.

**Pull request merged**
