### PR TITLE
802.1x ACLs

### PR DESCRIPTION
**Pull request by MichaelWasher**
Add ACL functionality to 802.1x ports
Add mininet tests to ensure functionality

### CODE REVIEW

**Comment by gizmoguy** [comment]
Needs a rebase to add support for chewie 0.0.15 after #2865 was merged

**Comment by MichaelWasher** [comment]
Resolved conflicts

**Comment by gizmoguy** [comment]
I see your tests are failing, this is because we updated the arguments for auth_handler() to have vlan_name, and filter_id.

See the following PRs:

https://github.com/faucetsdn/chewie/pull/120
https://github.com/faucetsdn/chewie/pull/118  

```
Traceback (most recent call last):
  File "/home/travis/build/faucetsdn/faucet/tests/unit/faucet/test_valve.py", line 1592, in test_handlers
    '0e:00:00:00:00:ff', faucet_dot1x.get_mac_str(valve_index, port_no))
TypeError: auth_handler() missing 2 required positional arguments: 'vlan_name' and 'filter_id'
```

**Comment by Bairdo** [comment]
~Also depending on what gets merged in first, #2896 or this~. 

Each new 8021X test needs this field:

```
DOT1X_EXPECTED_EVENTS = []
```

If it's empty it is not checked.

**Comment by SuTrello** [comment]
Hello, I found the sdn-authenticator project but i have a couple of doubts of the authentication with the web server. where can i find the password and the user´s list?

**Pull request merged**
