### PR TITLE
Upgrade to chewie 0.0.17.

### PR DESCRIPTION
**Pull request by gizmoguy**

### CODE REVIEW

**Comment by gizmoguy** [comment]
@MichaelWasher Looks like we have some failing faucet unit tests against new chewie, mind if you take a look when you get a chance?

```
======================================================================
FAIL: mininet_tests.Faucet8021XIdentityOnPortUpTest.test_untagged (subunit.RemotedTestCase)
mininet_tests.Faucet8021XIdentityOnPortUpTest.test_untagged
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 794, in test_untagged
    self.assertIn("Success", tcpdump_txt)
  File "/usr/lib/python3.6/unittest/case.py", line 1089, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: 'Success' not found in '07:01:18.150970 01:80:c2:00:00:03 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 23: EAP packet (0) v1, len 5, Request (1), id 150, len 5Type Identity (1)07:01:18.152250 56:d4:f3:e9:7b:41 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 27: EAP packet (0) v1, len 9, Response (2), id 150, len 9Type Identity (1), Identity: user07:01:20.153979 01:80:c2:00:00:03 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 23: EAP packet (0) v1, len 5, Request (1), id 29, len 5Type Identity (1)07:01:20.155222 56:d4:f3:e9:7b:41 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 27: EAP packet (0) v1, len 9, Response (2), id 29, len 9Type Identity (1), Identity: user07:01:51.338476 56:d4:f3:e9:7b:41 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 18: EAPOL start (1) v1, len 007:02:18.210353 01:80:c2:00:00:03 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 23: EAP packet (0) v1, len 5, Request (1), id 113, len 5Type Identity (1)07:02:18.211560 56:d4:f3:e9:7b:41 > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 27: EAP packet (0) v1, len 9, Response (2), id 113, len 9Type Identity (1), Identity: user7 packets captured7 packets received by filter0 packets dropped by kernel'
```

```
======================================================================
FAIL: mininet_tests.Faucet8021XPeriodicReauthTest.test_untagged (subunit.RemotedTestCase)
mininet_tests.Faucet8021XPeriodicReauthTest.test_untagged
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 828, in test_untagged
    self.scrape_prometheus_var('port_dot1x_success_total', labels=port_labels1, default=0))
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 4 != 1
```

**Comment by MichaelWasher** [comment]
@gizmoguy It honestly appears to be just this. I'm writing a small test in Chewie to make sure that we don't have a regression like this again and then I'll push up a pr.

https://github.com/MichaelWasher/chewie/commit/0fe94074ce292a041f2109f280dd75e8cf50df5e

**Comment by MichaelWasher** [comment]
One PR all prepped and ready. Sorry about the delay, takes a little to get my head around the packet dumps.
https://github.com/faucetsdn/chewie/pull/132

**Comment by gizmoguy** [comment]
All works now, thanks @MichaelWasher

**Pull request merged**
