### PR TITLE
dot1x get native vlan from radius

### LINKED ISSUE #2830: VLAN assignment via 802.1X/RADIUS
We would like FAUCET to be able to assign a port to a VLAN based on an access accept:

https://www.cisco.com/c/en/us/support/docs/wireless-mobility/wireless-vlan/71683-dynamicvlan-config.html

The RADIUS user attributes used for the VLAN ID assignment are:

IETF 64 (Tunnel Type)—Set this to VLAN.
IETF 65 (Tunnel Medium Type)—Set this to 802
IETF 81 (Tunnel Private Group ID)—Set this to VLAN ID.

### PR DESCRIPTION
**Pull request by Bairdo**
closes #2830 

requires https://github.com/faucetsdn/chewie/pull/118

test doesn't quite pass yet, when h1 logs on for second time onto vlan 2222.

### CODE REVIEW

**Comment by Bairdo** [comment]
eth_src & eth_dst table should also be tidied up - multiple entries for same eth_src on different vlans.

**Comment by Bairdo** [comment]
If the Radius attribute Tunnel-Private-Group-ID is in the access accept (handled by chewie) use it as the name of the VLAN to use as the native vlan on the port where the authentication occurred.

Chewie does not care about the other attributes Tunnel-Type or  Tunnel-Medium-Type, which possibly should be checked so that Tunnel-Private-Group-ID is to be interpreted as VLAN, but this is easy enough to add if desired.

The eth_src & eth_dst tables are cleared (for the port that is changing authentication status) on authentication status change or port down.

On port down or logoff the native vlan is returned to the original configs ('native_vlan').

1X Tests pass on OVS, X510, Cisco. Running full test suite now

**Comment by gizmoguy** [comment]
@Bairdo my memory fails me again, once I get your PR that upgrades faucet to chewie 0.0.15 shall I rerun the tests here and merge or were you not happy with how this was running on the hardware tests?

**Comment by gizmoguy** [comment]
Needs a rebase to add support for chewie 0.0.15 after #2865 was merged

**Comment by Bairdo** [comment]
this can wait till next release

**Comment by anarkiwi** [comment]
Looks like this needs a rebase.

**Comment by anarkiwi** [comment]
======================================================================
ERROR: test_handlers (__main__.ValveDot1xACLSmokeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/faucetsdn/faucet/tests/unit/faucet/test_valve.py", line 1542, in test_handlers
    '0e:00:00:00:00:ff', faucet_dot1x.get_mac_str(valve_index, port_no), vlan_name, filter_id)
  File "/home/travis/build/faucetsdn/faucet/faucet/faucet_dot1x.py", line 111, in auth_handler
    flowmods.extend(valve.add_dot1x_native_vlan(dot1x_port.number, str(address), vlan_name))
  File "/home/travis/build/faucetsdn/faucet/faucet/valve.py", line 1528, in add_dot1x_native_vlan
    ofmsgs.append(flood_table.flowdel(flood_table.match(vlan=vlan.vid)))
AttributeError: 'NoneType' object has no attribute 'vid'

**Pull request merged**
