### PR TITLE
Move unit, integration and generative tests to github from travis

### PR DESCRIPTION
**Pull request by mab68**

### CODE REVIEW

**Comment by mab68** [comment]
@gizmoguy 

Pretty sure I've got the github actions to mimic the Travis behaviour, so if worst comes to worst we can use that option.

I will investigate using the github workflow more.

**Comment by mab68** [comment]
Hey @gizmoguy, I think this should be good to go now.

**Comment by gizmoguy** [comment]
Concept looks good to me.

I see GitHub actions is emitting some warnings on your workflow definition, did you want to take a look at that?

```
 .github#L1

Received event from pull_request, but also received a before(f4e410346b2c90c44e8f0101f722ee02f3368726) or after(d9ec49f56a56f571782f37de896632a07fd5ed46) value.
 I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
```

**Comment by mab68** [comment]
> Concept looks good to me.
> 
> I see GitHub actions is emitting some warnings on your workflow definition, did you want to take a look at that?
> 
> ```
>  .github#L1
> 
> Received event from pull_request, but also received a before(f4e410346b2c90c44e8f0101f722ee02f3368726) or after(d9ec49f56a56f571782f37de896632a07fd5ed46) value.
>  I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
> ```

This is a problem with the file-changes-action. When a pull request is updated, it causes a pull-request synchronize event to occur which contains both the before & after information. I'll submit an issue to the action repository about this.

**Comment by gizmoguy** [comment]
#3230

**Pull request merged**
