### PR TITLE
BUGFIX: Chewie port never comes back up

### PR DESCRIPTION
**Pull request by MichaelWasher**
Add call to Chewie port_up

### CODE REVIEW

**Comment by anarkiwi** [comment]
=====================================================================
FAIL: mininet_tests.Faucet8021XPortStatusTest.test_untagged (subunit.RemotedTestCase)
mininet_tests.Faucet8021XPortStatusTest.test_untagged
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 661, in test_untagged
    require_host_learned=False, expected_result=False)
  File "/faucet-src/clib/mininet_test_base.py", line 1877, in one_ipv4_ping
    return self._one_ip_ping(host, ping_cmd, retries, require_host_learned, expected_result)
  File "/faucet-src/clib/mininet_test_base.py", line 1865, in _one_ip_ping
    msg='%s: %s' % (ping_cmd, ping_result))
  File "/usr/lib/python3.5/unittest/case.py", line 677, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : ping -c1  -Iuah1-eth0 10.0.0.3: PING 10.0.0.3 (10.0.0.3) from 10.0.0.1 uah1-eth0: 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=1 ttl=64 time=4.09 ms
--- 10.0.0.3 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.098/4.098/4.098/0.000 ms
----------------------------------------------------------------------
Ran 27 tests in 1143.162s

**Comment by anarkiwi** [comment]
Still failing:

FAIL: mininet_tests.Faucet8021XPortStatusTest.test_untagged (subunit.RemotedTestCase)
mininet_tests.Faucet8021XPortStatusTest.test_untagged
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 661, in test_untagged
    require_host_learned=False, expected_result=False)
  File "/faucet-src/clib/mininet_test_base.py", line 1877, in one_ipv4_ping
    return self._one_ip_ping(host, ping_cmd, retries, require_host_learned, expected_result)
  File "/faucet-src/clib/mininet_test_base.py", line 1865, in _one_ip_ping
    msg='%s: %s' % (ping_cmd, ping_result))
  File "/usr/lib/python3.5/unittest/case.py", line 677, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : ping -c1  -Iuae1-eth0 10.0.0.3: PING 10.0.0.3 (10.0.0.3) from 10.0.0.1 uae1-eth0: 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=1 ttl=64 time=4.19 ms
--- 10.0.0.3 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.195/4.195/4.195/0.000 ms

**Comment by MichaelWasher** [comment]
Failing on a Chewie issue. Refer to PR 102
https://github.com/faucetsdn/chewie/pull/102

**Comment by Bairdo** [comment]
https://github.com/faucetsdn/faucet/blob/master/faucet/faucet_dot1x.py#L155

This should be 'port_up' not 'port_down', probably got lost during a merge or something.

Also the Test class Faucet8021XPortFlapTest should have an attribute RADIUS_PORT = 1880
(without it may cause problem on software when running tests in parallel)


This passes on software but fails on hardware.

x510
```
mininet_tests.Faucet8021XPortFlapTest.test_untagged:
  output: "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py',\
    \ line 687, in test_untagged\t    self.assertIn('0 packets captured', tcpdump_txt_1)\t\
    AssertionError: '0 packets captured' not found in '00:57:45.731325 1e:f6:13:8f:70:6b\
    \ > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 18: EAPOL start (1) v1,\
    \ len 01 packet captured1 packet received by filter0 packets dropped by kernel'\t"
  status: FAIL
```

cisco
```
mininet_tests.Faucet8021XPortFlapTest.test_untagged:
  output: "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py',\
    \ line 687, in test_untagged\t    self.assertIn('0 packets captured', tcpdump_txt_1)\t\
    AssertionError: '0 packets captured' not found in '01:03:33.032062 0e:f4:98:04:ee:56\
    \ > 01:80:c2:00:00:03, ethertype EAPOL (0x888e), length 18: EAPOL start (1) v1,\
    \ len 01 packet captured1 packet received by filter0 packets dropped by kernel'\t"
  status: FAIL
```

I'll take another look later in the week.

**Pull request merged**
