### PR TITLE
Event no longer experimental

### PR DESCRIPTION
**Pull request by cglewis**
Boldly proposing that this feature is no longer experimental. I've been using it in many deployments and environments without issues for over a year.

### CODE REVIEW

**Comment by cglewis** [comment]
ok, travis is angry, I'll see if I can make it happier.

**Comment by cglewis** [comment]
Hmm, this test in the second job appears to be flakey:
```
FAIL: test_profile_reload (__main__.ValveReloadConfigProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/faucetsdn/faucet/tests/unit/faucet/test_valve.py", line 2315, in test_profile_reload
    self.assertTrue(total_tt_prop < 50, msg=pstats_text)
AssertionError: False is not true :          1241984 function calls (1235096 primitive calls) in 1.897 seconds
```
It passed for this PR on Travis under my fork, but it failed against faucetsdn/faucet.

@gizmoguy @anarkiwi when you get a chance can you try re-triggering that job and see if it passes?

**Comment by anarkiwi** [comment]
Hmm looks like yeah I need a better profile based test there.

Need to consult with our colleagues here to rename experimental.

**Comment by gizmoguy** [comment]
I'm okay dropping experimental, seems to work okay for me.

**Pull request merged**
