### PR TITLE
Update stack graph according to the stack link probe

### PR DESCRIPTION
**Pull request by trungdtbk**
This does not change any of the stack flooding algorithm. It simply add/remove edges in the stack graph (networkx).

### CODE REVIEW

**Comment by anarkiwi** [comment]
This looks like a positive and welcome addition, but we need tests to be able to accept it.

**Comment by trungdtbk** [comment]
Thanks for your comments. 
There's not much to test on this PR, I think. However, my next PR which implements the strategy as in email sent to Faucet-dev, will of course need tests.

**Comment by anarkiwi** [comment]
We can't accept the PR sorry without tests, as this PR does change behavior when probes are enabled and may affect production deployments.

**Comment by anarkiwi** [comment]
When tests are available, please update this PR (or open a new one).

**Pull request closed without merging**
